"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, load from environment variable
SECRET_KEY = 'django-insecure-pnfm_&zari###z@g98i5g35u%)i16+!9kdz1u@2(a@265n$))_'

# SECURITY WARNING: don't run with debug turned on in production!
# Set to False in production to prevent information disclosure
DEBUG = False

# Allow hosts from environment or configure for your domain
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'yourdomain.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'relationship_app',
    'bookshelf',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Note: django-csp can be added here for Content Security Policy:
    # 'csp.middleware.CSPMiddleware',
]
AUTH_USER_MODEL = 'bookshelf.CustomUser'    
# ============================================================================
# SECURITY SETTINGS
# ============================================================================

# CSRF Protection: Ensure CSRF tokens are required for state-changing requests
# This is enabled by default via CsrfViewMiddleware, but ensure cookies are secure
CSRF_COOKIE_SECURE = True  # Send CSRF cookie over HTTPS only
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript from accessing CSRF cookie
CSRF_TRUSTED_ORIGINS = ['https://*.yourdomain.com']  # Add trusted origins for CSRF

# Session Security: Ensure session cookies are sent over HTTPS only
SESSION_COOKIE_SECURE = True  # Send session cookie over HTTPS only
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript from accessing session cookie
SESSION_COOKIE_SAMESITE = 'Strict'  # Prevent CSRF via cookies

# Browser Security Headers: Prevent common XSS and clickjacking attacks
SECURE_BROWSER_XSS_FILTER = True  # Enable XSS filter in browsers (X-XSS-Protection)
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing (X-Content-Type-Options)
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking by disallowing framing (X-Frame-Options)

# Additional Security Headers
SECURE_HSTS_SECONDS = 31536000  # Force HTTPS for 1 year (Strict-Transport-Security)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to all subdomains
SECURE_HSTS_PRELOAD = True  # Allow inclusion in HSTS preload lists
SECURE_SSL_REDIRECT = True  # Redirect HTTP to HTTPS

# Proxy SSL Header: Trust X-Forwarded-Proto from reverse proxy
# Use this when running behind Nginx/Apache that handles HTTPS
# The proxy adds X-Forwarded-Proto header to indicate original request was HTTPS
# Django uses this to determine if request is secure for SECURE_SSL_REDIRECT and secure cookies
# Format: (header_name, header_value) - typically ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Content Security Policy (CSP) Headers
# This helps mitigate XSS attacks by controlling which domains can load content
# If using django-csp, configure CSP_DEFAULT_SRC and other directives
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", 'data:', 'https:')
CSP_FONT_SRC = ("'self'",)
CSP_CONNECT_SRC = ("'self'",)
CSP_FRAME_ANCESTORS = ("'none'",)

# Password Security: Use strong password hashing
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Preferred: Argon2
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',  # Fallback
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect after login/logout
LOGIN_REDIRECT_URL = '/relationship_app/books/'
LOGOUT_REDIRECT_URL = '/relationship_app/login/'

# ============================================================================
# SECURITY CHECKLIST AND NOTES
# ============================================================================
# 
# This configuration implements the following security measures:
#
# 1. DEBUG = False
#    - Prevents disclosure of sensitive information in error pages
#    - Set to True only during development
#
# 2. CSRF Protection
#    - CsrfViewMiddleware is enabled (protects against Cross-Site Request Forgery)
#    - All forms must include {% csrf_token %} tag
#    - CSRF_COOKIE_SECURE and SESSION_COOKIE_SECURE ensure cookies travel over HTTPS only
#
# 3. XSS Protection (Cross-Site Scripting)
#    - SECURE_BROWSER_XSS_FILTER enables X-XSS-Protection header
#    - SECURE_CONTENT_TYPE_NOSNIFF prevents MIME type sniffing
#    - Output should be auto-escaped in templates (default Django behavior)
#    - Use the |safe filter only on trusted content
#
# 4. Clickjacking Protection
#    - X_FRAME_OPTIONS = 'DENY' prevents embedding this site in iframes
#    - XFrameOptionsMiddleware is enabled
#
# 5. SQL Injection Prevention
#    - Always use Django ORM for queries (never string formatting with user input)
#    - Use parameterized queries: Model.objects.filter(field=user_input)
#    - Avoid raw() and raw SQL unless absolutely necessary
#
# 6. HTTPS/TLS
#    - SECURE_SSL_REDIRECT forces HTTP to HTTPS
#    - SECURE_HSTS_SECONDS enforces HSTS headers
#    - SESSION_COOKIE_SECURE and CSRF_COOKIE_SECURE require HTTPS
#
# 7. Password Security
#    - Argon2PasswordHasher (preferred) for strong hashing
#    - Password validators enforce minimum length and complexity
#
# Production Deployment Reminders:
# - Load SECRET_KEY from environment variable (os.environ.get('DJANGO_SECRET_KEY'))
# - Update ALLOWED_HOSTS with your actual domain
# - Use a web server (gunicorn, uWSGI) instead of Django's development server
# - Use a production database (PostgreSQL, MySQL) instead of SQLite
# - Enable HTTPS/TLS with a valid certificate
# - Regularly update Django and all dependencies
# - Perform security audits and penetration testing
#